language: php
php:
- '7.2'
install:
- composer require squizlabs/php_codesniffer
script:
- vendor/bin/phpcs --standard=PSR2 --ignore=src/Migrations src/
notifications:
  email:
  - yavuz@wildcodeschool.fr
branches:
  only:
  - master
  - dev